# report_generator.py
from fpdf import FPDF
import re
import os

def clean_text_for_pdf(text):
    """Remove emojis and unsupported Unicode for PDF compatibility"""
    if not isinstance(text, str):
        text = str(text)
    
    # Emoji replacements → plain text
    emoji_map = {
        "🎯": "[TARGET]",
        "✅": "[OK]",
        "❌": "[X]",
        "🔍": "[SEARCH]",
        "✨": "[STAR]",
        "📥": "[DOWNLOAD]",
        "📄": "[DOC]",
        "📊": "[CHART]",
        "💡": "[TIP]",
        "🛠️": "[TOOL]",
        "📝": "[NOTE]",
        "🔒": "[LOCK]"
    }
    
    # Unicode cleanup
    text = (text
        .replace('–', '-')    # en-dash
        .replace('—', '-')    # em-dash
        .replace('’', "'")    # smart quotes
        .replace('‘', "'")
        .replace('“', '"')
        .replace('”', '"')
        .replace('…', '...')
        .replace('\u200b', '')  # zero-width space
    )
    
    # Replace emojis
    for emoji, replacement in emoji_map.items():
        text = text.replace(emoji, replacement)
    
    return text

def generate_pdf_report(result, resume_filename="student"):
    try:
        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.set_font("Arial", size=12)
        
        # =============== HEADER ===============
        pdf.set_font("Arial", "B", 16)
        pdf.cell(0, 10, clean_text_for_pdf("ResumeBoost AI – Full Report"), ln=True, align="C")
        pdf.ln(5)
        
        # =============== ATS SCORE ===============
        pdf.set_font("Arial", "B", 14)
        score = result.get('ats_score', 0)
        color = (0, 100, 0) if score >= 70 else (180, 0, 0)
        pdf.set_text_color(*color)
        pdf.cell(0, 10, clean_text_for_pdf(f"ATS Score: {score}/100"), ln=True, align="C")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(5)
        
        # =============== ROLE ===============
        pdf.set_font("Arial", "", 12)
        role = result.get('detected_role', 'General')
        pdf.cell(0, 10, clean_text_for_pdf(f"Target Role: {role}"), ln=True, align="C")
        pdf.ln(10)
        
        # =============== KEYWORD GAPS ===============
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 10, "Missing Keywords", ln=True)
        pdf.set_font("Arial", "", 11)
        
        missing = result.get('missing_keywords', [])
        if missing:
            for kw in missing[:8]:
                pdf.cell(0, 8, f"• {clean_text_for_pdf(kw)}", ln=True)
        else:
            pdf.cell(0, 8, "[OK] None detected — great job!", ln=True)
        pdf.ln(5)
        
        # =============== SECTION SCORES ===============
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 10, "Section-wise Feedback", ln=True)
        pdf.set_font("Arial", "", 11)
        
        sections = result.get('section_scores', {})
        if sections:
            for sec, score in sections.items():
                status = "[OK] Good" if score >= 70 else "[X] Needs Work"
                pdf.cell(0, 8, f"- {sec.title()}: {score}/100 ({status})", ln=True)
        else:
            pdf.cell(0, 8, "[INFO] Section analysis unavailable", ln=True)
        pdf.ln(10)
        
        # =============== REWRITE SUGGESTION ===============
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 10, "Personalized Rewrite", ln=True)
        pdf.set_font("Arial", "", 11)
        
        # Get rewrite data
        before = result.get("weak_bullet", "Built a project.")
        after = result.get("rewrite_suggestion", 
                         f"Developed a {role} solution with quantifiable results.")
        
        pdf.cell(0, 8, f"Before: {clean_text_for_pdf(before)}", ln=True)
        pdf.set_font("Arial", "B", 11)
        pdf.set_text_color(0, 100, 0)
        pdf.cell(0, 8, f"After:  {clean_text_for_pdf(after)}", ln=True)
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Arial", "", 11)
        pdf.ln(5)
        
        # =============== SUGGESTIONS ===============
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 10, "Actionable Tips", ln=True)
        pdf.set_font("Arial", "", 11)
        
        suggestions = result.get('suggestions', [
            "[OK] Add quantifiable metrics (e.g., 'Improved accuracy by 12%')",
            "[TOOL] Use standard section headers (Skills, Projects, Education)",
            "[NOTE] Expand project descriptions with technologies used"
        ])
        
        for i, sug in enumerate(suggestions[:5], 1):
            pdf.cell(0, 8, f"{i}. {clean_text_for_pdf(sug)}", ln=True)
        
        # =============== FOOTER ===============
        pdf.ln(15)
        pdf.set_font("Arial", "I", 10)
        pdf.cell(0, 5, "Generated by ResumeBoost AI • Made for AIML Students", ln=True, align="C")
        pdf.cell(0, 5, "No resume data stored • Payment verified via Razorpay", ln=True, align="C")
        
        # =============== SAVE ===============
        filename = f"report_{resume_filename}_{score}.pdf"
        pdf.output(filename)
        return filename
        
    except Exception as e:
        # Fallback: Generate minimal PDF
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", size=12)
        pdf.cell(0, 10, "ResumeBoost AI Report (Fallback)", ln=True)
        pdf.cell(0, 10, f"Error: {str(e)}", ln=True)
        pdf.cell(0, 10, "Contact support: bittukrazad652@gmail.com", ln=True)
        
        filename = f"report_error_{resume_filename}.pdf"
        pdf.output(filename)
        return filename
