# report_generator.py — NEW FILE

from fpdf import FPDF
import os

def generate_pdf_report(result, resume_filename="resume"):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Header
    pdf.set_font("Arial", "B", 16)
    pdf.cell(200, 10, "ResumeBoost AI – Full Report", ln=True, align="C")
    pdf.ln(5)
    
    # ATS Score
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(0, 100, 0) if result['ats_score'] >= 70 else pdf.set_text_color(200, 0, 0)
    pdf.cell(200, 10, f"🎯 ATS Score: {result['ats_score']}/100", ln=True, align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)
    
    # Role
    pdf.set_font("Arial", "", 12)
    pdf.cell(200, 10, f"🔍 Target Role: {result['detected_role']}", ln=True, align="C")
    pdf.ln(10)
    
    # Keyword Gap
    pdf.set_font("Arial", "B", 12)
    pdf.cell(200, 10, "❌ Missing Keywords", ln=True)
    pdf.set_font("Arial", "", 11)
    for kw in result['missing_keywords'][:5]:
        pdf.cell(200, 8, f"• {kw}", ln=True)
    pdf.ln(5)
    
    # Section Scores
    pdf.set_font("Arial", "B", 12)
    pdf.cell(200, 10, "📊 Section-wise Feedback", ln=True)
    pdf.set_font("Arial", "", 11)
    for sec, score in result['section_scores'].items():
        status = "✅ Good" if score >= 70 else "⚠️ Needs Work"
        pdf.cell(200, 8, f"- {sec.title()}: {score}/100 ({status})", ln=True)
    pdf.ln(10)
    
    # AI Rewrite Example
    pdf.set_font("Arial", "B", 12)
    pdf.cell(200, 10, "✨ Suggested Rewrite", ln=True)
    pdf.set_font("Arial", "", 11)
    before = "Built a machine learning model."
    after = f"Developed a {result['detected_role']} solution using Python, achieving measurable impact."
    pdf.cell(200, 8, f"Before: {before}", ln=True)
    pdf.set_text_color(0, 100, 0)
    pdf.cell(200, 8, f"After:  {after}", ln=True)
    pdf.set_text_color(0, 0, 0)
    
    # Footer
    pdf.ln(20)
    pdf.set_font("Arial", "I", 10)
    pdf.cell(200, 10, "Generated by ResumeBoost AI — Made for AIML Students", ln=True, align="C")
    
    # Save
    filename = f"report_{resume_filename}.pdf"
    pdf.output(filename)
    return filename